### PR TITLE
feat: support tooltips on icon formatters

### PR DESCRIPTION
**Pull request by zewa666**
adds the possibility to define tooltips via the title tag on icon formatters

### CODE REVIEW

**Comment by zewa666** [comment]
this is just a minor feature but something I stumbled on the other day when working on a new feature.

**Comment by zewa666** [comment]
Supabase is quite interesting though I'd personally prefer Hasura. Have been using it with super great success for a larger project and would prefer that everytime again. The thing is, once persistance and handling CRUD becomes a free thing along with permissions etc, all handled by fundamental DB principles, nothing beats the productivity boost. Plus, I guess the GraphQL layer should nicely integrate with Slickgrid, though I have to admit I haven't yet tried so.

**Comment by ghiscoding** [comment]
ah yeah you mentioned it last time when we did the Header Menu thing. I think I'd also personally prefer GraphQL over OData, so Hasura make sense in this case. Thanks for the info

**Comment by ghiscoding** [comment]
@zewa666 
I think that the biggest challenge with Hasura would be to create the structure that I defined for the Pagination/Sorting/Filtering. I assume that's all doable in Hasura and perhaps we could create a new package in universal to support Hasura following this structure that I require. I'm just guessing here since I haven't tried anything and barely read their docs

**Comment by zewa666** [comment]
havent yet looked into slickgrids graphql backend but I guess it should be doable to adjust things to match Hasuras style.

the biggest pro with Hasura where it live-queries, aka graphql subscriptions but with server push on change. that alone is so very cool it could be worth the hassle (think of your realtime example)

Hasura cloud offers a free tier. as for db go for something like https://neon.tech/pricing

**Pull request merged**
