### PR TITLE
perf: Reduce iterative time complexity in Tree Data, fixes #1668

### LINKED ISSUE #1668: Reducing time complexity
### Describe the bug

We found that the due to the below code, the time complexity is O(n square) which can be reduced to O(n)

Modified code:
```
 DataView.getAllSelectedFilteredItems = function () {
      /* istanbul ignore if */
      if (!Array.isArray(this.selectedRowIds)) {
        return [];
      }

      const selectedRowIdSet = new Set(this.selectedRowIds); // Add new set 
      const intersection = this.filteredItems.filter((a) => selectedRowIdSet.has(a[this.idProperty]));
      return (intersection || []);
    }
```

### Reproduction

For large data set, the page hange for 1 minute

### Which Framework are you using?

React

### Environment Info

```shell
| Executable          | Version |
| ------------------- | ------- |
| (framework used)    | VERSION |
| Slickgrid-Universal | VERSION |
| TypeScript          | VERSION |
| Browser(s)          | VERSION |
| System OS           | VERSION |
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Vsinghal339-source**
fixes #1668

Optimize getAllSelectedFilteredItems and preSelectedRowIdsChangeFn with Set lookup and reducing time complexity from O(n square) to O(n)

### CODE REVIEW

**Comment by Vsinghal339-source** [comment]
@ghiscoding Please review this PR

**Comment by ghiscoding** [comment]
It looks good, thanks a lot for the contribution 😀 

Just out of curiosity, you said it was previously hanging for a minute. How long does it take after the fix, is it just a few seconds now?

**Comment by Vsinghal339-source** [comment]
for 40k records, the code was iterating over 40k * 40K recoreds which takes approx 30-40 seconds. We tried with 60k records and time exponentially increased to 1 minutes. But now it comes down to 400 ms.

Note: Even with new approach of Set(), although time is reduced to 400ms but it will still impact the sudden CPU spikes. We need to create the Set() of data only once and save it in globally under parent object and incrementally modify it. With this approach we can further optimise the app and reduce time from 400ms to < 1-2 ms

**Comment by ghiscoding** [comment]
Great, thanks for the explanation and of course if you find further improvement that can be made to improve performance then yes please contribute more PRs 😉

**Comment by Vsinghal339-source** [comment]
I would like to know when the next release will be made. Current version of the tag is v5.6.1. When will the newest tag (v5.6.2) be made?

**Comment by ghiscoding** [comment]
next weekend or the week after

**Pull request merged**
