### PR TITLE
fix: Join type

### LINKED ISSUE #1422: TypeScript type error cannot assign `unknown` to string...
### Describe the bug

I think the upgrade to the new TypeScript version created this new issue but only after I deleted the pnpm lock file and reinstalled everything

https://github.com/ghiscoding/slickgrid-universal/blob/5fab1792cfdf24172bd46556b6fe5513c93d19d1/packages/common/src/interfaces/column.interface.ts#L24-L28

image

### Reproduction

pnpm install and then run a TypeScript build

### Which Framework are you using?

Vanilla / Plain JS

### Environment Info

```shell
n/a
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-universal/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [Wikis](https://github.com/ghiscoding/slickgrid-universal/wiki).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-universal/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by zewa666**
fixes #1422

### CODE REVIEW

**Comment by zewa666** [comment]
I think this should do it. I couldn't really reproduce your original issue but, removing the // @ts-ignore reveleaded it as well for me. So now that one is also gone.

I've also made sure to add some tests if we need to test that further. So far my custom type assertions were enough but we might should go with something like tsd if we want to do more proper checks.

**Comment by zewa666** [comment]
ahh ok now I got ya. It doesn't fail in the IDE but when running `pnpm run bundle`. ok need to check more on that

**Comment by ghiscoding** [comment]
> ahh ok now I got ya. It doesn't fail in the IDE but when running `pnpm run bundle`. ok need to check more on that

hmm actually it failed when I ran the full Build and after going into the file, I did see the error in the IDE/VSCode as shown in the issue print screen. Also FYI, the reason this came up was that I deleted the pnpm lock file and deleted node_modules, because I wanted get rid of the `ip` package security issue (when a lock file exists, it sometime doesn't pick up version patch fixes).

**Comment by zewa666** [comment]
ok `rm -rf node_modules` might was the missing thing for me. Anyways, good the bundler caught it as well

**Comment by ghiscoding** [comment]
> ok `rm -rf node_modules` might was the missing thing for me. Anyways, good the bundler caught it as well

I'm a bit surprised, I thought that the lock file was enough to do the update, however I'm not even sure since when this error actually existed. I thought it was the latest TypeScript 5.4 that was released a couple days but as it turns out, the previous version also failed on this type... anyway, as long as we fixed it for the future :)

BTW, I saw Cypress failing again so I restarted it

**Comment by zewa666** [comment]
well if you can't repro it locally and the bundler cant either plus the original intent still is in place ... I'd say we're good until the next time ;)

**Comment by ghiscoding** [comment]
Thanks a lot for this PR, you even added more unit tests which is always very welcome... again thx for all your contributions :)

BTW, have you had a chance to try the Dark Mode yet? 😉

**Pull request merged**
